#undef ONESHOT_TIMEOUT
#define ONESHOT_TIMEOUT 1000

#define PERMISSIVE_HOLD

#define USB_SUSPEND_WAKEUP_DELAY 0
#define HOLD_ON_OTHER_KEY_PRESS
#define SERIAL_NUMBER "R6lJa/zLL5J3"
#define LAYER_STATE_8BIT

#define RGB_MATRIX_STARTUP_SPD 60

